project:
  type: website
  render:
    - cv.qmd
    - index.qmd
    - research.qmd
    - teaching.qmd
    - blog.qmd
    - blog
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Esteban Degetau"
  site-url: https://www.estebandegetau.com/
  description: "Esteban Degetau's Personal Website"
  repo-url: https://github.com/estebandegetau/estebandegetau.github.io
  google-analytics: "G-11D42BZNRY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
    right:
      - icon: rss
        href: index.xml


format: html

# brand: _brand.yml
